language: node_js
node_js:
  - "6.9.1"
before_script:
  - yarn global add gulp
script: gulp build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m "Automated push by Travis CI"
    git subtree push --prefix dist https://HoangPaul:$GITHUB_API_KEY@github.com/HoangPaul/intellibins gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
cache: yarn
